// <auto-generated />
using System;
using InformationFIle.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InformationFIle.Migrations
{
    [DbContext(typeof(InformationFIleContext))]
    [Migration("20181023134050_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InformationFIle.Models.Information", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Atrybuty");

                    b.Property<string>("CompanyName");

                    b.Property<string>("DataOstatniegoDostepu");

                    b.Property<string>("FileVersion");

                    b.Property<string>("ImportowaneBiblioteki");

                    b.Property<string>("Jezyk");

                    b.Property<string>("MD5");

                    b.Property<string>("Magic");

                    b.Property<string>("Nazwa");

                    b.Property<string>("OrginalnaNazwa");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Rozmiar");

                    b.Property<string>("Rozszerzenie");

                    b.Property<string>("SHA1");

                    b.Property<string>("SHA256");

                    b.Property<string>("VersionProduct");

                    b.HasKey("ID");

                    b.ToTable("Information");
                });
#pragma warning restore 612, 618
        }
    }
}
